In [2]:
import numpy as np
a = np.arange(36)
b = a.reshape(3, 3, 4)
print(b.dtype)
print(b.shape)
print(b)
print(b[0,0,2])

int64
(3, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]
2
