In [27]:
import numpy as np

a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape) # (3, 5)
print(a.ndim) # 2 -- 维度
print(a.dtype.name) # int64 数据类型
print(a.itemsize)
print(a.size)
print(type(a))

b = np.array([6, 7, 8])
print(b)
print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[6 7 8]
<class 'numpy.ndarray'>
